---
# Source: apim-helm-engine/templates/apim-templates.config.yaml
version: 0.0.1
apimServiceName: azure-api-management
apiVersionSets:
  - displayName: versionset-httpbin-api
    id: versionset-httpbin-api
    versionHeaderName: Accept-Version
    versioningScheme: Header
apis:
  - description: API Management facade for a very handy and free online HTTP tool
    name: httpBinAPI-v2
    openApiSpec: https://gist.githubusercontent.com/jdevillard/c3989391f3f1fa65a69a3da2a01c9a6e/raw/c9c8cb3128875528b6735325524a988dc8368c08/httpbin-org-v2.json
    serviceUrl: https://httpbin.org
    subscriptionRequired: false
    suffix: httpbin
    policy: ./all-operations.xml
    apiVersion: v2
    operations: 
      get: 
        policy: ./operations/get.xml
    products: starter
    apiVersionSetId: versionset-httpbin-api
namedValues:
products:
  - name: starter
    displayName: Starter  
tags:
backends:
linked: true
linkedTemplatesBaseUrl: https://linked-url
linkedTemplatesUrlQueryString: queryString
outputLocation: .